function [ Cd1_Pop,Cd2_Pop] = KS_AR( Cd1_Pop ,Cd2_Pop, Synaptic_p, time_step)
Vk = Synaptic_p.Vk;
M =Cd1_Pop.M;
g_conductance = Synaptic_p.g_Cd1_KS;
Cd1_Pop.I_KS = g_conductance.*(Cd1_Pop.Vm - Vk).*M;
g_conductance = Synaptic_p.g_Cd1_AR;
Cd1_Pop.I_AR = g_conductance./(1+exp((Cd1_Pop.Vm+75)./4)).*(Cd1_Pop.Vm - Vk);
M =Cd2_Pop.M;
g_conductance = Synaptic_p.g_Cd2_KS;
Cd2_Pop.I_KS = g_conductance.*(Cd2_Pop.Vm - Vk).*M;
g_conductance = Synaptic_p.g_Cd2_AR;
Cd2_Pop.I_AR = g_conductance./(1+exp((Cd2_Pop.Vm+75)./4)).*(Cd2_Pop.Vm - Vk);
M_inf = 1./(1.0+exp(-(Cd1_Pop.Vm+34)./6.5));
tao_M = 8./(exp(-(Cd1_Pop.Vm+55.0)./30.0)+exp((Cd1_Pop.Vm+55.0)./30.0));
Cd1_Pop.M = Cd1_Pop.M + (M_inf - Cd1_Pop.M)./tao_M.*time_step;
M_inf = 1./(1.0+exp(-(Cd2_Pop.Vm+34)./6.5));
tao_M = 8./(exp(-(Cd2_Pop.Vm+55.0)./30.0)+exp((Cd2_Pop.Vm+55.0)./30.0));
Cd2_Pop.M = Cd2_Pop.M + (M_inf - Cd2_Pop.M)./tao_M.*time_step;
